### ISSUE TITLE
[php] Same encryption with android, ios and php (Swift4)

### ISSUE THREAD

**Issue by GaruSivhuy** [krzyzanowskim/CryptoSwift#551] opened 2017-12-28 04:29 UTC
Hello,
I have problem with encrypt/decrypt with swift and php as detail below.

my extension in swift:

import Foundation
import CryptoSwift

extension String{
    
    func aesEncrypt(key: String, iv: String) throws -> String{
        let data = self.data(using: String.Encoding.utf8)
        let aes = try AES(key: key, iv: iv)
        let encrypted = try! aes.encrypt(Array(data!))
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()
    }
    
    func aesDecrypt(key: String, iv: String) throws -> String {
        let data = Data(base64Encoded: self)!
        let aes = try! AES(key: key, iv: iv)
        let decrypted = try! aes.decrypt(Array(data))
        let decryptedData = Data(decrypted)
        return String(bytes: decryptedData.bytes, encoding: .utf8) ?? "Could not decrypt"
    }  
}

<----------Code on View----------->
           let email = try txtUsername.text?.aesEncrypt(key: "abins5df78832439", iv: "abdfoi29782383dh")          
            
            print("encrypt email : \(email!,"")")
            
            let decryptEmail = try email!.aesDecrypt(key: "abins5df78832439", iv: "abdfoi29782383dh")
 
            print("decrypt email : \(decryptEmail,"")")
<---------------------------------------->
when i run on xcode it work perfect. 
results : encrypt/decrypt on ios
encrypt email : ("i+vglLubaK+VOjVBLeTOzw==", "")
decrypt email : ("admin@gmail.com", "")

however, i doesn't work with server side (php code)
the result from server side after decrypt : "admin@gmail.com\x01".
if i submit many time it will show :  "admin@gmail.com\x02x02x02"., "admin@gmail.com\x06x06x06x06x06x06". something like that.

<---------------------encrypt / decrypt in php -------------->
        private $iv  = 'abdfoi29782383dh'; 
	private $key = 'abins5df78832439'; 

	function encrypt($str) { 
	  $iv = $this->iv;

	  $td = mcrypt_module_open('rijndael-128', '', 'cbc', $iv);

	  mcrypt_generic_init($td, $this->key, $iv);
	  $encrypted = mcrypt_generic($td, $str);

	  mcrypt_generic_deinit($td);
	  mcrypt_module_close($td);

	  return base64_encode($encrypted);
	}

	function decrypt($code) {
	  $code = base64_decode($code);
	  $iv = $this->iv;

	  $td = mcrypt_module_open('rijndael-128', '', 'cbc', $iv);

	  mcrypt_generic_init($td, $this->key, $iv);
	  $decrypted = mdecrypt_generic($td, $code);

	  mcrypt_generic_deinit($td);
	  mcrypt_module_close($td);

	  return utf8_encode(trim($decrypted));
	}
}
<------------------------------------------------------>

Code you please help me? I really new for iOS. (android is work fine.)

**Comment by krzyzanowskim** [comment] 2017-12-29 11:32
Have you seen this thread https://github.com/krzyzanowskim/CryptoSwift/issues/20 ?

**Comment by krzyzanowskim** [comment] 2017-12-30 15:51
closing as duplicate #20

**Closed by krzyzanowskim** 2017-12-30 15:51 UTC
Labels: integration

**Comment by tierracero** [comment] 2018-06-16 13:44
issue esas the key length 


    func encr() throws -> String {
        let key = "" // length == 32
        let iv = "" // length == 16
        let data = self.data(using: .utf8)!
        let encrypted = try! AES(key: key.bytes, blockMode: .CBC(iv: iv.bytes), padding: .pkcs7).encrypt([UInt8](data))
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()
    }

    func decr() throws -> String {
        et key = "" // length == 32
        let iv = "" // length == 16
        let data = Data(base64Encoded: self)!
        let decrypted = try! AES(key: key.bytes, blockMode: .CBC(iv: iv.bytes), padding: .pkcs7).decrypt([UInt8](data))
        let decryptedData = Data(decrypted)
        return String(bytes: decryptedData.bytes, encoding: .utf8) ?? "Could not decrypt"
    }

**Comment by nightfreak** [comment] 2019-12-27 01:30
@GaruSivhuy the problem is the padding in PHP

correct php code would be:

```
function decrypt($code) {
  $code = base64_decode($code);
  $iv = $this->iv;

  $td = mcrypt_module_open('rijndael-128', '', 'cbc', $iv);

  mcrypt_generic_init($td, $this->key, $iv);
  $decrypted = mdecrypt_generic($td, $code);

  $pad = ord($decrypted[($len = strlen($decrypted)) - 1]);
  $decrypted = substr($decrypted, 0, strlen($decrypted) - $pad);

  mcrypt_generic_deinit($td);
  mcrypt_module_close($td);

  return utf8_encode(trim($decrypted));
}
```

**Comment by karansoni725** [comment] 2021-05-18 06:30
Can you please share android code with me
