### ISSUE TITLE
update to swift4.0 error

### ISSUE THREAD

**Issue by linkjd** [krzyzanowskim/CryptoSwift#537] opened 2017-11-17 06:43 UTC
I`m already update to swift4.0, then get some error, like “'expandKey' is inaccessible due to 'private' protection level”, "'calculateSBox' is inaccessible due to 'private' protection level", "Cannot call value of non-function type 'Int32'"

**Comment by krzyzanowskim** [comment] 2017-11-17 08:27
It looks like you're not using Swift4 compiler to build CryptoSwift

Closing as duplicate of #521 #523 #527 #531 #533

**Closed by krzyzanowskim** 2017-11-17 08:27 UTC

**Comment by linkjd** [comment] 2017-11-17 09:32
OK, Thank you very much
