### ISSUE TITLE
Can't convert to new api

### ISSUE THREAD

**Issue by ssaguiar** [krzyzanowskim/CryptoSwift#515] opened 2017-10-11 18:07 UTC
Sorry to ask such question here, but I don't know where I could.

I was using CryptoSwift in a project but hen I updated the Xcode to version 9, the code presented several errors in CryptoSwift, so I updated it to master branch.

Now I don't find how to make the code work with the new api and feel stupid, sorry.

The code I used was:

	class func decryptDataFromServer(decryptdata: DecryptData) -> Bool {
		var licence_key_Data: Data?
		var licence_iv_Data: Data?
		var license_load_Data: Data?
		var licence_iv_Byte = [UInt8]()
		var decryptedLoad_Byte = [UInt8]()
		var license_load_str: String? = ""
		var license_load_64: Data?
		var decryptedKeyData: Data?
		var json = [Any]()
		
                // LICENSE is a variable where the license is. It is encrypted with a public key. After decrypting it we will have the private key and will be able to decode the other data we want (server address and some other stuff). 

		guard let base64Decoded = Data(base64Encoded: LICENSE, options: []) else {
			return false
		}

        let streamLength = Int(base64Decoded.count)

		licence_key_Data = base64Decoded.subdata(in: 0..<256) // .withUnsafeBytes {$0.pointee}
		licence_iv_Data = base64Decoded.subdata(in: 256..<272) // .withUnsafeBytes {$0.pointee}
		license_load_Data = base64Decoded.subdata(in: 272..<streamLength) // .withUnsafeBytes {$0.pointee}
        
		license_load_64 = (license_load_Data!.base64EncodedData(options: NSData.Base64EncodingOptions.endLineWithLineFeed))
		license_load_str = String(data: license_load_64!, encoding: .utf8)!
        
        
		licence_iv_Byte = (licence_iv_Data?.bytes)!
		
		decryptedKeyData = RSAUtils.decryptWithRSAPublicKey(licence_key_Data!, pubkeyBase64: PUBLIC_KEY, keychainTag: TAG_PUBLIC_KEY)!
        
        
		if decryptedKeyData?.count != 0 { // Was decrypted?
			decryptedLoad_Byte = (decryptedKeyData?.bytes)!
			
			let data = Data(base64Encoded: license_load_str!)!
			let decrypted = try! AES(key: decryptedLoad_Byte, iv: licence_iv_Byte).decrypt([UInt8](data))
			
			let decryptedData = Data(decrypted)
			
			do {
				json = try JSONSerialization.jsonObject(with: decryptedData, options: []) as! [Any]
			} catch {
				return false
			}
			
			let licenseData = json[2] as! [String]
			
			decryptdata.setStartDate(startDate: NSString(format: "%@", json[0] as! CVarArg) as String)
			decryptdata.setEndDate(endDate: NSString(format: "%@", json[1] as! CVarArg) as String)
			decryptdata.setServerData(serverData: licenseData[0])
			decryptdata.setServerKey(serverKey: licenseData[1])
		} else {
			return false
		}
		
		return true
	}

The error happens at

		decryptedKeyData = RSAUtils.decryptWithRSAPublicKey(licence_key_Data!, pubkeyBase64: PUBLIC_KEY, keychainTag: TAG_PUBLIC_KEY)!

Somebody could help me to find some example on how to do this?
Thanks a lot.

**Comment by krzyzanowskim** [comment] 2017-10-13 21:21
RSAUtils is not a part of CryptoSwift. You question is too general. Try to make it easy to address please

**Comment by krzyzanowskim** [comment] 2017-10-15 21:50
Closing, I'm not even sure if the issue is related to CryptoSwift at all.

**Closed by krzyzanowskim** 2017-10-15 21:50 UTC
