### ISSUE TITLE
Crash with SHA-3 256

### ISSUE THREAD

**Issue by afriedman94** [krzyzanowskim/CryptoSwift#518] opened 2017-10-16 18:03 UTC
Crash in SHA3.swift line 276. 

`accumulated[markByteIndex] |= 0x06 // 0x1F for SHAKE`

Index out of bounds error. 

This was due to  `if accumulated.count == 0 || accumulated.count % blockSize != 0 { ... }`

Not handling the case for `if markByteIndex == accumulated.count`

Is a possible fix for this: 

```
if markByteIndex == accumulated.count {
                let q = blockSize
                accumulated += Array<UInt8>(repeating: 0, count: q)
            }


???
```

**Comment by krzyzanowskim** [comment] 2017-10-16 19:31
What is the input to get the crash? I'd need to write test for that.

**Comment by krzyzanowskim** [comment] 2017-10-20 02:10
Any update on that? how is this reproducible?

**Comment by afriedman94** [comment] 2017-10-20 13:29
Hey sorry. I don't have the original input to reproduce it.. 
All I know is that `markByteIndex == accumulated.count`. Which was causing the crash.

**Comment by krzyzanowskim** [comment] 2017-10-22 06:24
Can't reproduce, I'd love to hear if it can be reproduced. For now I'm closing.

**Closed by krzyzanowskim** 2017-10-22 06:24 UTC
