### ISSUE TITLE
XCode 9.1 compiles with 37 errors

### ISSUE THREAD

**Issue by Pacana78** [krzyzanowskim/CryptoSwift#534] opened 2017-11-14 16:27 UTC
Hi,

I added CryptoSwift with the podfile, and when I try to compile the project I got a bunch of errors, just to mention some:
'expandKey' is inaccessible due to 'private' protection level 
 'variantNr' is inaccessible due to 'private' protection level
'calculateSBox' is inaccessible due to 'private' protection level
all in AES.swift

Thanks for your help

**Comment by krzyzanowskim** [comment] 2017-11-14 16:29
U have to use Swift 4 compiler.

Closing as duplicate of #521 #523 #527 #531 #533

**Closed by krzyzanowskim** 2017-11-14 16:29 UTC

**Comment by Pacana78** [comment] 2017-11-14 16:37
Thanks

**Comment by cilvet** [comment] 2017-12-21 15:16
I changed to Swift 4.0 compiler and I'm still getting these same results. Any Idea what I might be doing wrong?

**Comment by krzyzanowskim** [comment] 2017-12-21 17:30
The CryptoSwift target must use Swift 3.2 mode.

**Comment by zhouhao27** [comment] 2018-01-26 03:54
@krzyzanowskim I do the reverse. The main project no change still swift 3.2. But cryptorSwift target 4.0.
