### ISSUE TITLE
ios 10.3 bug

### ISSUE THREAD

**Issue by miadparizadian** [krzyzanowskim/CryptoSwift#772] opened 2019-11-04 11:36 UTC
hi 
im using  aes 256 cbc in iphone 5 (ios 10.3)
but encryption has been problem
3 is right up to the first encryption and others wrong
how to fix theme????!!!!!!
this is fource

**Comment by krzyzanowskim** [comment] 2019-11-04 11:54
Looks like LLVM bug discussed here https://github.com/krzyzanowskim/CryptoSwift/issues/748#issuecomment-547363969

**Comment by miadparizadian** [comment] 2019-11-04 12:13
> Looks like LLVM bug discussed here [#748 (comment)](https://github.com/krzyzanowskim/CryptoSwift/issues/748#issuecomment-547363969)

What does llvm mean and how to solve it؟؟

**Comment by krzyzanowskim** [comment] 2019-11-04 12:15
LLVM in short means: it's a compiler bug. Not much you acn do. Likely fix will be released soon and available in Xcode.

**Comment by miadparizadian** [comment] 2019-11-04 12:17
> LLVM in short means: it's a compiler bug. Not much you acn do. Likely fix will be released soon and available in Xcode.

in xcode 11 has problem???

**Comment by krzyzanowskim** [comment] 2019-11-04 17:13
> in xcode 11 has problem???

I don't know, I'm not updated about Apple products anyway.

**Comment by krzyzanowskim** [comment] 2019-11-06 08:35
Closing this issue as a duplicate of #748

**Closed by krzyzanowskim** 2019-11-06 08:35 UTC
