### ISSUE TITLE
Multiple errors when compiling in xcode 9.2 

### ISSUE THREAD

**Issue by popularizan** [krzyzanowskim/CryptoSwift#581] opened 2018-02-26 15:55 UTC
# Details

- CryptoSwift version: 0.8.1
- Swift version: 4
- Platform version: 
	- [x ] iOS/tvOS/watchOS
	- [ ] macOS
	- [ ] Linux
- Installation: 
	- [ x] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description

Multiple errors when compiling in xcode 9.2 and swift 4, to 32 errors.

../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:75:62: 'expandKey' is inaccessible due to 'private' protection level
../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:76:65: 'expandKeyInv' is inaccessible due to 'private' protection level
.../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:78:82: 'calculateSBox' is inaccessible due to 'private' protection level
.../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:223:14: 'F1' is inaccessible due to 'private' protection level
.../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:224:14: 'F1' is inaccessible due to 'private' protection level

etc... !!

# Steps to reproduce

Sample code:

```swift
import CryptoSwift


```

**Comment by krzyzanowskim** [comment] 2018-02-26 15:56
Duplicate of #521 #523 #527 #531 #576

**Closed by krzyzanowskim** 2018-02-26 15:56 UTC
