### ISSUE TITLE
With version 1.3.7: Distribution failed with errors

### ISSUE THREAD

**Issue by TofPlay** [krzyzanowskim/CryptoSwift#843] opened 2020-11-26 17:29 UTC
**Describe the bug**
<img width="745" alt="2020-11-26-18-18-15-ax83y-screenshot" src="https://user-images.githubusercontent.com/1082222/100378842-2d27e300-3014-11eb-8ad1-50dbc37789ea.png">

CryptoSwift.framework exist in `Frameworks` folder and `PlugIns` folder

Xcode Version 12.2 (12B45b)
macOS Big Sur 11.0.1 (20B29)

**Reproduce**
Steps to reproduce:
1. Create an iOS project
2. Add an extension Notification
3. Install CryptoSwift 1.3.7 under "Swift Packages" 
4. Create an Archive
5. Validate the archive

**Comment by krzyzanowskim** [comment] 2020-11-26 18:38
this is Xcode update issue. You need delete product/derived data etc directory, otherwise artefacts from previous version stays and results in duplicated entries. Look at this: https://stackoverflow.com/a/64858213/699944

**Comment by TofPlay** [comment] 2020-11-27 12:03
@krzyzanowskim thanks for your answer. I understand it's an issue with Xcode right.
Just one thing:
Creating an XCFramework like you did is the right thing to do. On the other hand, an XCFramework is binary, so don't put that in git. Some do it anyway and after a few versions when we make a git clone we end up downloading several hundred MB.
What you have to do is put the Package.swift file on git and put the zip file of the XCFramework on a CDN in https (very important the https!)
If it can help you I made a little script [framework2swiftpm](https://github.com/TofPlay/framework2swiftpm)  that will undoubtedly help you.

**Comment by krzyzanowskim** [comment] 2020-11-27 12:23
>  so don't put that in git.

Unfortunately, It's in the repo on purpose. Xcode has problems with downloadable archives, unfortunately (as of Xcode 12.2) - lesson learned.

**Comment by TofPlay** [comment] 2020-11-27 12:28
Strange because for my part I have because personally I created a repo with just Package.swift and put the zip of the XCFramework in a CDN and I had no problems using it via Xcode. He downloaded it used like any other package.

**Comment by krzyzanowskim** [comment] 2020-11-27 16:18
yea, strange indeed. It started with zip archive (1.3.4, 1.3.5), then some users start to report Xcode can't unscrew itself and result in either broken binary or build, and only put it in the repository unscrew Xcode. There're corner cases where it fails and I'm tired of Xcode support tbh. Maybe next year with Xcode 13 I'll try archives again.

**Comment by krzyzanowskim** [comment] 2020-11-27 16:20
in any case, did the clean build folder solve the initial issue for you @TofPlay ?

**Comment by TofPlay** [comment] 2020-11-28 10:39
No I went back to version 1.3.3 the one before the XCFramework with just the sources

**Comment by krzyzanowskim** [comment] 2020-11-28 10:43
can you give it a shot after derived data and build directory deleted? (this is the kind of Xcode issues I deal since xcframework)
That'd be a valuable insight whether there's new issue

**Comment by llKoull** [comment] 2020-11-30 16:27
Hi! 

I'm having the same issue. I tried to use the version 1.3.3 but it's not solved 😟

May i do anything else?

Thanks and best regards,

**Comment by krzyzanowskim** [comment] 2020-11-30 16:36
@llKoull did you look into https://github.com/krzyzanowskim/CryptoSwift/issues/843#issuecomment-734438653 ? It looks like the Xcode issue, and requires manual cleanup build/deriveddata folders

**Comment by llKoull** [comment] 2020-11-30 16:37
@krzyzanowskim yes, i tried to remove the derived data and fully clean my project but i'm always getting the same error :S

**Comment by krzyzanowskim** [comment] 2020-11-30 16:46
It looks like it's still somewhere. also make sure to clear spm cache. How does the bundle content looks like? is this different issue?

**Comment by llKoull** [comment] 2020-11-30 16:46
i finally removed the dependency from SPM and used cocoapods instead and it worked.

**Comment by krzyzanowskim** [comment] 2020-11-30 17:08
christ, this SPM 🤪 I'd like to get to the root of the problem though and figure if there anything I can do, or just cry on the how SPM works in Xcode

**Comment by llKoull** [comment] 2020-11-30 17:24
Hehehe I'm also having a lot of issues with of Xcode 12. I don't know why but i have to be cleaning the derived data and the project almost everytime. Xcode did become very slow and it's really difficult to use it with big storyboards (tried with my macbook pro with an i9 and my imac with an i7 both with 16GB of ram).

I think that we should start crying together 😆

**Comment by mohpor** [comment] 2020-12-01 12:22
I am facing the issue too. Resetting Module cache, cleaning Derived Data folder, ... Nothing worked. Had to add it via Pods. And, I didn't have it before, so the idea of the problem being from upgrades couldn't be right.

**Comment by krzyzanowskim** [comment] 2020-12-01 12:39
can you by any chance reproduce it and share the project with me so I can take a look at it on my side please?

**Comment by mohpor** [comment] 2020-12-01 12:44
It's nothing I can share unfortunately, but I'm happy to share any kind of logs you need. The problem is when I try to Upload to the AppStore connect, so it works normally but the there are bundle id collisions. I have more than 1 target in my archive. (Share Extension, Broadcast Extension...) but it is only being used in the main App.

**Comment by krzyzanowskim** [comment] 2020-12-01 12:47
so it runs in simulator, it runs on device, but when archived for itunes connect it's broken?

**Comment by mohpor** [comment] 2020-12-01 14:59
No it's not broken when you archive. It evens Archives successfully but, when you try to Upload to AppStore Connect, it gest rejected by API because of the Bundle Identifier Collisions.


<img width="747" alt="Screen Shot 2020-12-01 at 6 24 45 PM" src="https://user-images.githubusercontent.com/4954588/100756961-0ba76c80-3403-11eb-9b8c-02d24389e937.png">

**Comment by krzyzanowskim** [comment] 2020-12-01 15:06
I meant it archives successfully yet invalid bundle. I don't understand it tbh. It's not the problem with 1.3.3?

**Comment by mohpor** [comment] 2020-12-01 15:22
I didn't have CryptoSwift in my project before today. It's the first version I tried with this project. I've used CryptoSwift with other projects in the past, but with Pods. I will try to help find a solution for it.

**Comment by krzyzanowskim** [comment] 2020-12-01 17:13
damn it. I just published 1.3.8 where I reverted binary target distribution, back to sources. This should bring back sanity to the project.

**Comment by Reiszecke** [comment] 2020-12-04 01:34
This was driving me nuts. Just went through 2 hours of googling, 10 recent commits, `derived data delete`s and `clean builder folder`s and `autocreate schemes now`s. Every time I stumbled across the commit that had CryptoSwift in it I was like "nah man that ain't gonna be it".

I even checked if 1.3.7 had an update and thought "ok, 1.3.8 can't be THAT much different" until I've read the commit's message and checked out this issue. Worked.

Anyway, thank you for being so responsive on this issue and **thank you for providing us with this library. You are a genius.** <3

**Comment by krzyzanowskim** [comment] 2020-12-12 21:44
I guess I can close this issue now. Thank you everywone!

**Closed by krzyzanowskim** 2020-12-12 21:44 UTC
