### ISSUE TITLE
SIGABRT when using CryptoSwift in XCode workspace

### ISSUE THREAD

**Issue by AlexDM0** [krzyzanowskim/CryptoSwift#420] opened 2017-04-05 15:49 UTC
First of all, thanks for the lib! We're happily using it over at github.com/crownstone! I have my lib which uses cryptoswift in a workspace with an app that is using the lib. All package management is done using carthage. If I compile the app from within the workspace I get SIGABRT crash on encrypt or decrypt using aes128 ctr. I tried copy pasting exactly the code you use in the unit test and the result is the same.

0.6.1 is the last version I know of that did not have this problem. 

Do you have any idea what could cause this?

Cheers

**Comment by krzyzanowskim** [comment] 2017-04-05 16:08
Do you have a project I could look at?

**Comment by AlexDM0** [comment] 2017-04-05 16:14
Err not directly since the bluenet-lib-ios and bluenet-lib-dev (which show the problem) only decrypt once a ble event from our hardware comes in. 

The setup is:
```
workspace [
  |
  |__ single page app (has carthage dependency lib)
  |
  |_ lib (has carthage dependency CryptoSwift)
```

I do a carthage update --platform iOS --no-use-binaries on the lib and the single page app.

The single page app runs perfectly when i open just it's project and build it. If I run it from the workspace it gives the sigabrt.

I'll see if I can set up a small example soon, I already wasted half my day figuring out this was the issue :)

**Comment by krzyzanowskim** [comment] 2017-04-08 05:28
The example would be helpful and save me a time to setup the environment.

**Comment by krzyzanowskim** [comment] 2017-04-10 07:20
you really should come with the copu&paste example I can use to debut the issue.

**Comment by krzyzanowskim** [comment] 2017-04-10 07:37
Regarding https://github.com/krzyzanowskim/CryptoSwift/issues/422 @AlexDM0 can you try without carthage?

**Comment by AlexDM0** [comment] 2017-04-10 08:13
Hi, sorry, it's really busy at work and I don't have time to do this right now. We use Carthage for all our dependencies so I'd really rather not treat this module any differently. 

Sorry I can't be of more help

**Comment by krzyzanowskim** [comment] 2017-04-10 08:22
Carthage had issues in the past, so that's something to exclude that factor.

**Comment by xandros6** [comment] 2017-04-10 08:24
I see that the problem is with kylef/JSONWebToken framework that use a different version of CryptoSwift

**Comment by krzyzanowskim** [comment] 2017-04-30 17:59
I cannot reproduce the setup, thus the problem. Can't say if the problem is related to the setup, carthage or cryptoswift projct. Closing the issue. Feel free to reopen if you can provide the sample project.

**Closed by krzyzanowskim** 2017-04-30 17:59 UTC
