### ISSUE TITLE
AES encrypt, CFB mode, segment_size support?

### ISSUE THREAD

**Issue by haonv206** [krzyzanowskim/CryptoSwift#500] opened 2017-09-22 08:22 UTC
Server side (python) required encrypt with segment_size:
`AES.new(key, AES.MODE_CFB, iv, segment_size=24).encrypt(plain)`
I tried many ways but cant find the segment_size support in this lib

**Comment by krzyzanowskim** [comment] 2017-09-22 08:26
the segmented CFB mode is not supported, would be nice to have it probably.

**Comment by haonv206** [comment] 2017-09-22 10:51
Do you have any plan for this, in near future?

**Comment by NathanFallet** [comment] 2020-05-20 19:06
Any update on this? I need to use CFB with 8 bits (CFB8) instead of 128 because the server is using CFB8 and I can't change this... (I need to conform to the server protocol)

**Comment by PlugNCS** [comment] 2020-05-21 10:06
I would also need at least the CFB8 format support to work on my project

**Comment by NathanFallet** [comment] 2020-05-31 23:08
I spent some time inspecting CFB and AES classes; If I understand well, the changes starts here: https://github.com/krzyzanowskim/CryptoSwift/blob/938d7973b022735f1e9ec9ee6cf44a6ccc43c641/Sources/CryptoSwift/AES.swift#L146

Classic AES is using 128 bits, so 16 bytes, so there are 16 variables calculated.
In the case of CFB8 for example, it's 8 bits, so 1 byte, so only `b00` should be calculated.

Now the question is how to implement it? I thought about adding a parameter `segment_size` to `BlockMode` which is always 128, except for CFB where it can be 1, 8 or 128. Then checking this parameter in `encrypt` and `decrypt` functions should do the trick to adapt how the work is done.

@krzyzanowskim What do you think of this? If you think it's the right way, I can start working on this and submit a PR as soon as it's implemented. Else, I'm opened to your suggestions.

**Comment by myke91** [comment] 2020-11-19 09:00
@NathanFallet 
Were you able to get a solution to this problem? I also need support for CFB8

**Comment by NathanFallet** [comment] 2020-11-19 09:34
@myke91 I'm going to see this weekend if I can implement the solution I though about (I was waiting for an answer from lib's owner but nothing), and we'll see if it gets merged

**Comment by krzyzanowskim** [comment] 2020-11-19 09:45
I'm sorry I kissed that. yea, PR would be great! really appreciate you input

**Comment by NathanFallet** [comment] 2020-12-02 10:58
I've tried to implement my solution, but it seems to be more difficult that I though. I'm going to study the AES algorithm in details to figure out why it doesn't work, and how I should make my changes.

**Comment by NathanFallet** [comment] 2020-12-02 11:11
Also @krzyzanowskim could you provide me documentations you used to write the implementation of the AES algorithm?

**Comment by NathanFallet** [comment] 2021-03-01 19:57
After a deeper study of the AES algorithm and its cipher modes, I now have all the technical details about how the CFB algorithm works, and I will try a new fix (this time targeting the correct part of the code)
And by the way I share this book from which I learnt a lot about AES and cryptography in general, and can be useful for many of contributors here: https://www.crypto-textbook.com (_Understand Cryptography_, by Christof Paar and Jan Pelzl)

**Comment by NathanFallet** [comment] 2021-03-02 08:45
@krzyzanowskim The PR is ready for review.
I also tested CFB8 encryption using my branch in my project's Package.swift, and it works perfectly as intended.

**Closed** 2021-03-23 19:12 UTC
Labels: enhancement
