### ISSUE TITLE
Broken SwiftPackage

### ISSUE THREAD

**Issue by idoodler** [krzyzanowskim/CryptoSwift#842] opened 2020-11-23 07:37 UTC
**Describe the bug**
The last merge broke the Swift Package.

**Reproduce**
Steps to reproduce:
1. Add the latest master to your
2. Build

Here is the link to the failed Github Action: https://github.com/krzyzanowskim/CryptoSwift/runs/1438655269

**Comment by krzyzanowskim** [comment] 2020-11-23 11:33
it's weird, it does work when I add it to the Xcode

<img width="1618" alt="Screen Shot 2020-11-23 at 12 32 14" src="https://user-images.githubusercontent.com/758033/99957478-0e152100-2d88-11eb-889f-299221e71034.png">

**Comment by krzyzanowskim** [comment] 2020-11-23 11:48
no, I can't reproduce this thig, can you @idoodler? how

**Comment by krzyzanowskim** [comment] 2020-11-23 12:08
update to 1.3.7 and PLEASE report back. Closing for now.

**Closed by krzyzanowskim** 2020-11-23 12:08 UTC
Labels: bug

**Comment by idoodler** [comment] 2020-11-23 12:33
> no, I can't reproduce this thig, can you @idoodler? how

We use gitlab CI/CD for our Buildserver, every build checks out the project and thus reinitializes the SwiftPackage. We get the following error.

``
downloaded archive of binary target 'CryptoSwift' does not contain expected binary artifact 'CryptoSwift.xcframework'
``

We are currently trying it again, I will keep you updated.

**Comment by idoodler** [comment] 2020-11-23 13:10
@krzyzanowskim Everything is fine again
