### ISSUE TITLE
Issue with AES ECB 256 encryption in iOS version less than 11

### ISSUE THREAD

**Issue by shahnawaz2057** [krzyzanowskim/CryptoSwift#771] opened 2019-11-04 09:17 UTC
I am using this  library to perform AES 256 ECB encryption to encrypt password. Everything works fine in my local environment. But strangely enough, when I upload the app to Test Flight, this encryption doesn't work in iOS version below 11 (It works in iOS version >= 11). It return some different encrypted text in Test flight build than my local build for the same string. Therefore encrypted string from TestFlight build cannot be decrypted back using the key which was used while encryption.

This issue we are encountering from past 1 month. Is it a known issue? can help to resolve this.

I am using Swift 3.2, branch swift32 version = 0.7.0

(Everything works fine for iOS >= 11)

Thanks

**Comment by krzyzanowskim** [comment] 2019-11-04 11:53
Is it maybe run on 32bit devices?

**Comment by shahnawaz2057** [comment] 2019-11-04 13:39
Yeah it looks like as the affected device is iPhone5 and iPad2. But the encryption was working on these device till last month for my app store app. 

This encryption still works on these devices if i deploy the app through fabric beta for SIT or UAT, but as soon as i distribute it through iTuneConnect, problem starts for these target devices.

Appreciate your suggestion to resolve this issue.
Thanks

**Comment by krzyzanowskim** [comment] 2019-11-04 14:04
that's because appstore recompile your binary from the bitcode, and this process is broken

**Comment by shahnawaz2057** [comment] 2019-11-04 14:24
ok. does this mean this library cannot be used for 32 bit devices any more. or is there any fix possible to resolve this issue.

Thanks

**Comment by krzyzanowskim** [comment] 2019-11-04 17:14
There is possible way to mitigate the issue by trying different code constructs, hoping it won't trigger the compilation bug. I don't have 32bit device to test it though, and new Apple Watch Series 3 where it is reproducible (I was told) is $200 that I don't have for this project.

**Comment by shahnawaz2057** [comment] 2019-11-05 04:08
Ok. Can share the code construct if possible so that I try here locally to see if this resolved the issue.
Appreciate your help.

Thanks

**Comment by krzyzanowskim** [comment] 2019-11-05 13:37
I don't know what triggers the issue exactly though. it's hide and seek.

**Comment by krzyzanowskim** [comment] 2019-11-06 08:36
Closing as duplicate of #748

**Closed by krzyzanowskim** 2019-11-06 08:36 UTC
