### ISSUE TITLE
Padding for AES128 CTR not working

### ISSUE THREAD

**Issue by AlexDM0** [krzyzanowskim/CryptoSwift#424] opened 2017-04-13 14:16 UTC
Hi,

Last version I used before updating to the 0.6.8 was 0.6.1. Back here, the padding was also working for CTR and our code depends on it to do this.

In 0.6.8, this is no longer the case.

Is this a mistake or should this be postprocessed in my own code? I can't seem to set the .PaddingRequired option manually either.

Regards

**Comment by krzyzanowskim** [comment] 2017-04-13 16:15
This may be the cause https://github.com/krzyzanowskim/CryptoSwift/commit/bea5cc1bcea6f943c0f8ac29c9555276c72582ff#commitcomment-21113157

are you able to come up with test for this?

**Comment by krzyzanowskim** [comment] 2017-04-13 16:18
is #420 related to this by any chance?

**Comment by AlexDM0** [comment] 2017-04-18 09:59
Quite simply encrypt payload length 17 (blocksize + 1) with aes.ctr and check the length of the encrypted result. If it's not 32 then its wrong.

**Comment by krzyzanowskim** [comment] 2017-04-18 10:01
@AlexDM0 sure, can you please try to revert change to this line 
 https://github.com/krzyzanowskim/CryptoSwift/commit/bea5cc1bcea6f943c0f8ac29c9555276c72582ff#diff-1262a6479146de1876b8c357a12dbe1fR429 and confirm it's the fix?

**Comment by AlexDM0** [comment] 2017-04-18 10:27
I tried it and it does not work.

**Comment by krzyzanowskim** [comment] 2017-04-18 10:30
ok. Can you please paste the code here? I'll use it as test. Do you call .finish() at the end?

**Comment by AlexDM0** [comment] 2017-04-18 10:33
I have my own unit tests in my lib which I tried with the commit you mentioned. I can make a quick test and do a pull request with it?

**Comment by krzyzanowskim** [comment] 2017-04-18 10:34
sure, just PR against "develop" branch

**Comment by AlexDM0** [comment] 2017-04-18 12:43
I've made #425

**Comment by krzyzanowskim** [comment] 2017-04-30 08:53
hm... looks like the change I mentioned previously is https://github.com/krzyzanowskim/CryptoSwift/commit/bea5cc1bcea6f943c0f8ac29c9555276c72582ff#diff-1262a6479146de1876b8c357a12dbe1fR429 is the trouble one @AlexDM0 

i need to figure out the workaround. Should be fixed later today.

**Comment by krzyzanowskim** [comment] 2017-04-30 10:03
Fixed https://github.com/krzyzanowskim/CryptoSwift/commit/3d49da4b00187aa634630ae07fe49efc3c609133

**Closed by krzyzanowskim** 2017-04-30 10:03 UTC
Labels: bug
