### ISSUE TITLE
UInt64Extension uses a deprecated function from Generics

### ISSUE THREAD

**Issue by tapz** [krzyzanowskim/CryptoSwift#65] opened 2015-05-14 18:12 UTC
.../Pods/CryptoSwift/CryptoSwift/UInt64Extension.swift:23:16: 'integerWithBytes' was deprecated in * version 0.8

**Comment by krzyzanowskim** [comment] 2015-05-14 23:04
thx. duplicate of https://github.com/krzyzanowskim/CryptoSwift/issues/50

**Closed by krzyzanowskim** 2015-05-14 23:04 UTC
