### ISSUE TITLE
 'expandKey' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by hanishassim** [krzyzanowskim/CryptoSwift#576] opened 2018-02-15 03:42 UTC
# Details

- CryptoSwift version: 0.8.1
- Swift version: 4
- Platform version: 
	- [X] iOS/tvOS/watchOS
	- [ ] macOS
	- [ ] Linux
- Installation: 
	- [X] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description
Happen on line 71 of AES.swift

# Steps to reproduce
Build a swift 4 project with cryptoswift installed with cocoapods, will encounter this error.

Sample code:
```
private lazy var expandedKey: Array<Array<UInt32>> = self.expandKey(self.key, variant: self.variant)
private lazy var expandedKeyInv: Array<Array<UInt32>> = self.expandKeyInv(self.key, variant: self.variant)
```

**Comment by krzyzanowskim** [comment] 2018-02-15 09:22
Duplicate of #521 #523 #527 #531

**Closed by krzyzanowskim** 2018-02-15 09:22 UTC
